#!/bin/bash

if [ -e ./running_stage ]; then
	echo Deploy Running scheduled another
	echo +1 > ./running_stage
	exit 0
fi

touch ./running_stage

set -e

./deploy cameo-stage 172.16.23.2:5000 172.16.23.130

if [ -s ./running_stage ]; then
	echo Deploy scheduled, running it now
	rm ./running_stage
	./deploy_stage
else
	rm ./running_stage
fi
