#!/bin/bash

if [ -e ./running_www ]; then
	echo Deploy Running scheduled another
	echo +1 > ./running_www
	exit 0
fi

touch ./running_www

set -e

./deploy cameo-www-dev 172.16.23.2:5000 172.16.23.129 dev.cameo.io 9001
./deploy cameo-www-dev 172.16.23.2:5000 172.16.23.130 dev.cameo.io 9001
#./deploy cameowww 172.16.42.4:5000 172.16.42.15 -update-www

if [ -s ./running_www ]; then
	echo Deploy scheduled, running it now
	rm ./running_www
	./deploy_www
else
	rm ./running_www
fi
