#!/bin/bash

registry="172.16.23.2:5000"

backendKey=$(redis-cli -h 172.16.23.130 keys \* | grep backend)
instancesDev=$(redis-cli -h 172.16.23.130 smembers $backendKey | grep -v dummy |  sed 's/:80//')

backendKey=$(redis-cli -h 172.16.23.124 keys \* | grep backend)
instancesStage=$(redis-cli -h 172.16.23.124 smembers $backendKey | grep -v dummy |  sed 's/:80//')

instances=( ${instancesDev[@]} ${instancesStage[@]} )


for instance in "${instances[@]}"; do
        echo -e "\e[32m[CameoDeploy - Stoping instance ${instance} ]\033[0m"
        ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null deploy@${instance} "sudo /opt/cameoScripts/dockerHost/stop.sh cameowww"
done

for instance in "${instances[@]}"; do
        echo -e "\e[32m[CameoDeploy - Deploying on instance ${instance} ]\033[0m"
	ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null deploy@${instance} "sudo /opt/cameoScripts/dockerHost/run.sh --registry=${registry} --update-www"
done
