#!/bin/bash

if [ -e ./running_www ]; then
	echo Deploy Running scheduled another
	echo +1 > ./running_www
	exit 0
fi

touch ./running_www

set -e

./deploy cameo-www 172.16.23.2:5000 172.16.23.130 -update-www
./deploy cameo-www 172.16.23.2:5000 172.16.23.124 -update-www

if [ -s ./running_www ]; then
	echo Deploy scheduled, running it now
	rm ./running_www
	./deploy_www
else
	rm ./running_www
fi
