#!/bin/bash

if [ -e ./running_prod ]; then
	echo Deploy Running scheduled another
	echo +1 > ./running_prod
	exit 0
fi

touch ./running_prod

set -e

./deploy cameo-prod 172.16.42.4:5000 172.16.42.15 www.cameonet.de

if [ -s ./running_prod ]; then
	echo Deploy scheduled, running it now
	rm ./running_prod
	./deploy_prod
else
	rm ./running_prod
fi
